name: CI

on: [push]

jobs:
  build-enabler:
    name: Build the application for enabler
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: enabler
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install modules
        run: npm ci

      - name: Compile typescript
        run: npm run build

      - name: Execute tests
        run: npm run test

  build-processor:
    name: Build the application for processor
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: processor
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install modules
        run: npm ci

      - name: Compile typescript
        run: npm run build

      - name: Execute tests
        run: npm run test